#!/bin/bash


DIR="/home/pi/alarmclock"

cd $DIR 
action="$1"

if pgrep "web.py" > /dev/null  
then
    STATUS="active"
else
    STATUS="stopped"
fi

# if action not supplied at the command prompt
# display usae message and die
[ $# -eq 0 ] && { echo "Usage: $0 start|stop|status"; exit 0; }
	
# start web.py and exit script
if [ $1 = "start" ];then  
    if [ $STATUS = "active" ];then
        echo "alarmclock allready active"
        exit 0
    else
        echo "starting alarmclock"
        ${DIR}/web.py &> /dev/null & 
        exit 0
    fi
#stop web.py and exit script
elif [ $1 =  "stop" ];then
    if [ $STATUS = "stopped" ];then
        echo "alarmclock is not active"
        exit 0
    else 
        echo "stopping alarmclock"
        pkill web.py
        pkill mplayer
        exit 0
    fi
#status web.py and exit script
elif [ $1 = "status" ] ; then
    echo "alarmclock $STATUS"
    exit 0 
fi

exit 1
